version: '3.1'
services:
  django-tutorial:
    container_name: contenedor_jenkins
    image: danie164/jenkins  
    restart: always
    environment:
      ALLOWED_HOSTS: "*"
      HOST: db_mariadb
      USUARIO: django
      CONTRA: django
      BASE_DATOS: django
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.org
    ports:
      - 8086:8006
    depends_on:
      - db
  db:
    container_name: contenedor_mariadbjenkins
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: django
    volumes:
      - jenkins:/var/lib/mysql
volumes:
    jenkins:
